version: '3'
services:
  app:
    build: .
    command: npm run start-dev
    volumes:
      - .:/usr/app/
      - node_modules:/usr/app/node_modules
    ports:
      - "3002:3002"
      - "8888:8888"
    environment:
      PORT: 3002
      NODE_ENV: development
      SESSION_SECRET: 'secret'

volumes:
  node_modules:
